<script setup lang="ts">
import { VList, VListItem, VDivider } from 'vuetify/components';
</script>

<template>
  <v-list density="compact" nav>
    <v-list-item
      link
      prepend-icon="mdi-view-dashboard"
      title="Dashboard"
      value="dashboard"
      to="/dashboard"
    />
    <v-divider />
    <v-list-item
      link
      prepend-icon="mdi-account-group"
      title="Alunos"
      value="students"
      to="/students"
    />
    <v-list-item
      link
      prepend-icon="mdi-human-male-board"
      title="Professores"
      value="teachers"
      to="/teachers"
    />
    <v-list-item
      link
      prepend-icon="mdi-calendar-month"
      title="Aulas"
      value="music-classes"
      to="/music-classes"
    />
    <v-list-item
      link
      prepend-icon="mdi-guitar-acoustic"
      title="Instrumentos"
      value="instruments"
      to="/instruments"
    />
    <v-divider />
    <v-list-item
      link
      prepend-icon="mdi-certificate"
      title="Matrículas"
      value="registrations"
      to="/registrations"
    />
    <v-list-item
      link
      prepend-icon="mdi-cash-multiple"
      title="Financeiro"
      value="payments"
      to="/payments"
    />
    <v-list-item
      link
      prepend-icon="mdi-clipboard-list"
      title="Presença"
      value="attendances"
      to="/attendances"
    />
    <v-list-item
      link
      prepend-icon="mdi-chart-line"
      title="Desempenho"
      value="performance-reports"
      to="/performance-reports"
    />
  </v-list>
</template>